"""The exact receiver-side rollback helper against a temporary filesystem."""

from __future__ import annotations

import hashlib
import json
import os
from pathlib import Path
import time

import pytest

from custom_components.enigma2_mqtt import installer_helper
from custom_components.enigma2_mqtt.installer_helper import (
    PACKAGE,
    STALE_LOCK_SECONDS,
    boot_id,
    claim_transaction,
    prune_snapshots,
    read_identity,
    release_transaction,
    restore,
    snapshot,
    uptime,
    verify_manifest,
)

WEBIF_DIR = "usr/lib/enigma2/python/Plugins/Extensions/WebInterface/WebChilds/External"
PLUGIN_DIR = "usr/lib/enigma2/python/Plugins/Extensions/MQTTBridge"


def _write(root: Path, relative: str, value: str) -> Path:
    target = root / relative
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(value, encoding="utf-8")
    return target


def _receiver_tree(root: Path) -> None:
    _write(
        root,
        "usr/lib/opkg/status",
        f"Package: unrelated\nVersion: 7\n\nPackage: {PACKAGE}\nVersion: 0.0.9\nDescription: old\n",
    )
    _write(root, f"usr/lib/opkg/info/{PACKAGE}.list", "/old/plugin.py\n")
    _write(root, "usr/lib/opkg/info/unrelated.list", "/keep\n")
    _write(
        root,
        "usr/lib/enigma2/python/Plugins/Extensions/MQTTBridge/plugin.py",
        "old plugin\n",
    )
    _write(
        root,
        "usr/lib/enigma2/python/Plugins/Extensions/WebInterface/WebChilds/External/MQTTBridge.py",
        "old shim\n",
    )
    _write(
        root,
        "usr/lib/enigma2/python/Plugins/Extensions/WebInterface/"
        "WebChilds/External/__pycache__/MQTTBridge.cpython-312.pyc",
        "old bytecode\n",
    )
    _write(
        root,
        "etc/enigma2/settings",
        "config.misc.keep=true\n"
        "config.plugins.mqttbridge.host=old-broker\n"
        "config.plugins.mqttbridge.port=1883\n",
    )
    _write(root, "etc/enigma2/mqttbridge.json", '{"old":true}\n')


def _move_opkg_database(root: Path, base: str) -> None:
    """Move the database where an image's own opkg.conf says it is.

    OpenViX 6.6: `/usr/lib/opkg` exists and holds `alternatives/` and nothing else,
    while `/etc/opkg/opkg.conf` names `/var/lib/opkg`. The empty directory is part of
    the fixture, because it is what made the hard-coded path look plausible.
    """
    legacy = root / "usr/lib/opkg"
    target = root / base
    target.parent.mkdir(parents=True, exist_ok=True)
    legacy.rename(target)
    (legacy / "alternatives").mkdir(parents=True)


def _write_opkg_conf(root: Path, base: str) -> None:
    _write(
        root,
        "etc/opkg/opkg.conf",
        "# generated by the image\n"
        "src/gz all http://feeds.example.invalid/all\n"
        "dest root /\n"
        f"option lists_dir /{base}/lists\n"
        f"option info_dir /{base}/info\n"
        f"option status_file /{base}/status\n",
    )
    # Architectures live in their own file on this image, and say nothing about paths.
    _write(root, "etc/opkg/arch.conf", "arch all 1\narch mips32el 10\n")


def test_the_database_is_found_where_the_image_says_it_is(tmp_path: Path) -> None:
    """The layout the guided installer died on, snapshotted and rolled back."""
    root = tmp_path / "root"
    backup = tmp_path / "backup"
    _receiver_tree(root)
    _move_opkg_database(root, "var/lib/opkg")
    _write_opkg_conf(root, "var/lib/opkg")

    metadata = snapshot(root, backup)

    assert metadata["package_status"] is True
    assert metadata["opkg_info"] is True

    _write(
        root,
        "var/lib/opkg/status",
        f"Package: unrelated\nVersion: 8\n\nPackage: {PACKAGE}\nVersion: 0.1.0\n",
    )
    _write(root, f"var/lib/opkg/info/{PACKAGE}.list", "/new/plugin.py\n")

    restore(root, backup, restore_provisioning=True, restore_settings=True)

    status = (root / "var/lib/opkg/status").read_text(encoding="utf-8")
    assert f"Package: {PACKAGE}\nVersion: 0.0.9" in status
    assert "Package: unrelated\nVersion: 8" in status
    assert (root / f"var/lib/opkg/info/{PACKAGE}.list").read_text() == "/old/plugin.py\n"
    # The empty directory that used to be mistaken for the database is untouched.
    assert list((root / "usr/lib/opkg").iterdir()) == [root / "usr/lib/opkg/alternatives"]


def test_a_status_file_anywhere_the_configuration_names(tmp_path: Path) -> None:
    """The option is the answer, not a hint to be checked against a default."""
    root = tmp_path / "root"
    backup = tmp_path / "backup"
    _receiver_tree(root)
    _move_opkg_database(root, "opt/packages/db")
    _write_opkg_conf(root, "opt/packages/db")

    snapshot(root, backup)
    _write(root, "opt/packages/db/status", f"Package: {PACKAGE}\nVersion: 0.1.0\n")

    restore(root, backup, restore_provisioning=True, restore_settings=True)

    assert (
        f"Package: {PACKAGE}\nVersion: 0.0.9"
        in (root / "opt/packages/db/status").read_text(encoding="utf-8")
    )


def test_an_image_without_an_opkg_configuration_keeps_the_old_layout(
    tmp_path: Path,
) -> None:
    """Which is every image this was written against, and none of them may break."""
    root = tmp_path / "root"
    _receiver_tree(root)

    paths = installer_helper.opkg_paths(root)

    assert paths.status == root / "usr/lib/opkg/status"
    assert paths.info == root / "usr/lib/opkg/info"


def test_the_configured_database_wins_over_an_old_one_left_behind(tmp_path: Path) -> None:
    """An image that moved its database may well have left the old files there."""
    root = tmp_path / "root"
    _receiver_tree(root)
    _write(root, "var/lib/opkg/status", f"Package: {PACKAGE}\nVersion: 9.9.9\n")
    _write_opkg_conf(root, "var/lib/opkg")

    paths = installer_helper.opkg_paths(root)

    assert paths.status == root / "var/lib/opkg/status"


def test_a_snapshot_without_a_database_says_where_it_looked(tmp_path: Path) -> None:
    """"No such file" names a path; this has to name the ones it considered."""
    root = tmp_path / "root"
    backup = tmp_path / "backup"
    _receiver_tree(root)
    (root / "usr/lib/opkg/status").unlink()

    with pytest.raises(FileNotFoundError) as raised:
        snapshot(root, backup)

    message = str(raised.value)
    assert "var/lib/opkg/status" in message
    assert "usr/lib/opkg/status" in message


def test_a_configured_status_file_that_is_missing_names_itself(tmp_path: Path) -> None:
    """And does not offer the defaults, which the configuration has ruled out."""
    root = tmp_path / "root"
    backup = tmp_path / "backup"
    _receiver_tree(root)
    _write_opkg_conf(root, "var/lib/opkg")

    with pytest.raises(FileNotFoundError) as raised:
        snapshot(root, backup)

    message = str(raised.value)
    assert "var/lib/opkg/status" in message
    assert "usr/lib/opkg/status" not in message


def test_a_configuration_that_points_outside_the_tree_is_refused(tmp_path: Path) -> None:
    """The one path in this module that comes out of a file rather than a constant."""
    root = tmp_path / "root"
    backup = tmp_path / "backup"
    _receiver_tree(root)
    _write(root, "etc/opkg/opkg.conf", "option status_file /../../escape/status\n")

    with pytest.raises(ValueError, match="unusable path"):
        snapshot(root, backup)


def test_a_later_configuration_file_overrides_the_main_one(tmp_path: Path) -> None:
    """Which is what opkg does, and the only rule that makes this predictable."""
    root = tmp_path / "root"
    _receiver_tree(root)
    _write_opkg_conf(root, "var/lib/opkg")
    _write(root, "etc/opkg/zz-local.conf", "option status_file /opt/db/status\n")

    assert installer_helper.opkg_paths(root).status == root / "opt/db/status"


def test_restore_preserves_unrelated_package_and_settings(tmp_path: Path) -> None:
    root = tmp_path / "root"
    backup = tmp_path / "backup"
    _receiver_tree(root)
    metadata = snapshot(root, backup)
    assert metadata == {
        "schema": 2,
        "plugin": True,
        "package_status": True,
        "opkg_info": True,
        "provisioning": True,
        "settings": True,
        "webif_shim": True,
        "webif_cache": True,
    }

    _write(
        root,
        "usr/lib/opkg/status",
        "Package: unrelated\nVersion: 8\n\n"
        "Package: newly-installed-unrelated\nVersion: 1\n\n"
        f"Package: {PACKAGE}\nVersion: 0.1.0\n",
    )
    _write(root, f"usr/lib/opkg/info/{PACKAGE}.list", "/new/plugin.py\n")
    _write(
        root,
        "usr/lib/enigma2/python/Plugins/Extensions/MQTTBridge/plugin.py",
        "new plugin\n",
    )
    _write(
        root,
        "usr/lib/enigma2/python/Plugins/Extensions/WebInterface/WebChilds/External/MQTTBridge.py",
        "new shim\n",
    )
    old_cache = (
        root / "usr/lib/enigma2/python/Plugins/Extensions/WebInterface/"
        "WebChilds/External/__pycache__/MQTTBridge.cpython-312.pyc"
    )
    old_cache.write_text("new bytecode\n", encoding="utf-8")
    _write(
        root,
        "etc/enigma2/settings",
        "config.misc.keep=changed-concurrently\nconfig.plugins.mqttbridge.host=new-broker\n",
    )
    _write(root, "etc/enigma2/mqttbridge.json", '{"new":true}\n')

    restore(root, backup, restore_provisioning=True, restore_settings=True)

    status = (root / "usr/lib/opkg/status").read_text()
    assert "Package: unrelated\nVersion: 8" in status
    assert "Package: newly-installed-unrelated\nVersion: 1" in status
    assert f"Package: {PACKAGE}\nVersion: 0.0.9" in status
    assert "Version: 0.1.0" not in status
    assert (root / f"usr/lib/opkg/info/{PACKAGE}.list").read_text() == "/old/plugin.py\n"
    assert (root / "usr/lib/opkg/info/unrelated.list").read_text() == "/keep\n"
    assert (
        root / "usr/lib/enigma2/python/Plugins/Extensions/MQTTBridge/plugin.py"
    ).read_text() == "old plugin\n"
    assert (
        root / "usr/lib/enigma2/python/Plugins/Extensions/WebInterface/"
        "WebChilds/External/MQTTBridge.py"
    ).read_text() == "old shim\n"
    assert old_cache.read_text(encoding="utf-8") == "old bytecode\n"
    settings = (root / "etc/enigma2/settings").read_text()
    assert "config.misc.keep=changed-concurrently" in settings
    assert "config.plugins.mqttbridge.host=old-broker" in settings
    assert "config.plugins.mqttbridge.host=new-broker" not in settings
    assert (root / "etc/enigma2/mqttbridge.json").read_text() == '{"old":true}\n'


def test_a_rollback_puts_back_the_plugin_and_the_mode_it_was_left_in(
    tmp_path: Path,
) -> None:
    """The first drill over a plugin that was already installed, undone.

    Every earlier drill ran against a receiver with no plugin on it, where a rollback
    restores „there was nothing here". This is the other case: a plugin that had been
    installed and configured, whose Home Assistant entry had since been deleted — so
    the plugin had been told `ha_mode: off` and was sitting there working, announcing
    nothing. An install over it writes a provisioning file that asks for `integration`,
    and a rollback has to leave the receiver in the state that install found it in,
    which includes the mode. Its settings are also a real box's: ten lines, with no
    `base_topic` among them, because it had never been moved off the default.
    """
    root = tmp_path / "root"
    backup = tmp_path / "backup"
    _receiver_tree(root)
    _write(
        root,
        "etc/enigma2/settings",
        "config.misc.keep=true\n"
        "config.plugins.mqttbridge.host=old-broker\n"
        "config.plugins.mqttbridge.node_id=vuuno4kse_005301\n"
        "config.plugins.mqttbridge.ha_mode=off\n",
    )
    # The plugin deletes its provisioning file as it imports it, so a box that has been
    # configured for a while has none.
    (root / "etc/enigma2/mqttbridge.json").unlink()

    metadata = snapshot(root, backup)
    assert metadata["plugin"] is True
    assert metadata["provisioning"] is False

    _write(root, f"{PLUGIN_DIR}/plugin.py", "new plugin\n")
    _write(root, "etc/enigma2/mqttbridge.json", '{"ha_mode":"integration"}\n')
    _write(
        root,
        "etc/enigma2/settings",
        "config.misc.keep=true\n"
        "config.plugins.mqttbridge.host=new-broker\n"
        "config.plugins.mqttbridge.node_id=vuuno4kse_005301\n"
        "config.plugins.mqttbridge.ha_mode=integration\n",
    )

    restore(root, backup, restore_provisioning=True, restore_settings=True)

    assert (root / PLUGIN_DIR / "plugin.py").read_text() == "old plugin\n"
    settings = (root / "etc/enigma2/settings").read_text()
    assert "config.plugins.mqttbridge.ha_mode=off" in settings
    assert "ha_mode=integration" not in settings
    assert "config.plugins.mqttbridge.host=old-broker" in settings
    assert "config.plugins.mqttbridge.node_id=vuuno4kse_005301" in settings
    # Absent before, absent after: a rollback that invented a line here would be
    # configuring the receiver, not putting it back.
    assert "base_topic" not in settings
    assert "config.misc.keep=true" in settings
    assert not (root / "etc/enigma2/mqttbridge.json").exists()


def test_restore_removes_only_new_openwebif_shim(tmp_path: Path) -> None:
    root = tmp_path / "root"
    backup = tmp_path / "backup"
    _receiver_tree(root)
    shim = (
        root / "usr/lib/enigma2/python/Plugins/Extensions/WebInterface/"
        "WebChilds/External/MQTTBridge.py"
    )
    shim.unlink()
    for bytecode in shim.parent.joinpath("__pycache__").glob("MQTTBridge.*.pyc"):
        bytecode.unlink()
    sibling = _write(root, str(shim.parent.relative_to(root) / "OtherPlugin.py"), "keep\n")

    metadata = snapshot(root, backup)
    assert metadata["webif_shim"] is False
    shim.write_text("new package shim\n", encoding="utf-8")
    generated = _write(
        root,
        str(shim.parent.relative_to(root) / "__pycache__/MQTTBridge.cpython-312.pyc"),
        "new bytecode\n",
    )

    restore(root, backup, restore_provisioning=True, restore_settings=True)

    assert not shim.exists()
    assert not generated.exists()
    assert sibling.read_text(encoding="utf-8") == "keep\n"


def test_restore_removes_the_bytecode_the_receiver_actually_writes(tmp_path: Path) -> None:
    """This image compiles the hook into the legacy location, beside the source.

    `opkg remove` deletes the files it installed, which are the `.py` files, so the
    rollback of a first install restores "there was no hook here" — and used to leave
    `MQTTBridge.pyc` sitting next to where the source had been. Python imports a
    legacy-location `.pyc` as a complete module, so the hook stayed importable and
    would have gone looking for a plugin that is no longer installed.
    """
    root = tmp_path / "root"
    backup = tmp_path / "backup"
    _receiver_tree(root)
    shim = root / WEBIF_DIR / "MQTTBridge.py"
    shim.unlink()
    for bytecode in (root / WEBIF_DIR / "__pycache__").glob("MQTTBridge.*.pyc"):
        bytecode.unlink()

    metadata = snapshot(root, backup)
    assert metadata["webif_shim"] is False
    assert metadata["webif_cache"] is False

    shim.write_text("new shim\n", encoding="utf-8")
    legacy = _write(root, f"{WEBIF_DIR}/MQTTBridge.pyc", "new bytecode\n")

    restore(root, backup, restore_provisioning=True, restore_settings=True)

    assert not shim.exists()
    assert not legacy.exists()


def test_the_legacy_bytecode_goes_back_where_the_receiver_put_it(tmp_path: Path) -> None:
    """A rollback restores both locations, and does not confuse one for the other."""
    root = tmp_path / "root"
    backup = tmp_path / "backup"
    _receiver_tree(root)
    legacy = _write(root, f"{WEBIF_DIR}/MQTTBridge.pyc", "old bytecode\n")
    cache = root / WEBIF_DIR / "__pycache__/MQTTBridge.cpython-312.pyc"

    assert snapshot(root, backup)["webif_cache"] is True

    legacy.write_text("new bytecode\n", encoding="utf-8")
    cache.write_text("new bytecode\n", encoding="utf-8")

    restore(root, backup, restore_provisioning=True, restore_settings=True)

    assert legacy.read_text(encoding="utf-8") == "old bytecode\n"
    assert cache.read_text(encoding="utf-8") == "old bytecode\n"
    assert not (root / WEBIF_DIR / "__pycache__/MQTTBridge.pyc").exists()


def test_restore_of_a_first_install_removes_the_whole_plugin_directory(
    tmp_path: Path,
) -> None:
    """Including bytecode no build ever shipped, and the vendored subtree.

    `setup.pyc` is on a real receiver because somebody opened the setup screen once,
    so the set of compiled files is not the set of files of any one build. What proves
    the plugin is gone is the directory, never a list of names.
    """
    root = tmp_path / "root"
    backup = tmp_path / "backup"
    _receiver_tree(root)
    plugin = root / PLUGIN_DIR
    (plugin / "plugin.py").unlink()
    plugin.rmdir()

    assert snapshot(root, backup)["plugin"] is False

    _write(root, f"{PLUGIN_DIR}/plugin.py", "new\n")
    _write(root, f"{PLUGIN_DIR}/plugin.pyc", "bytecode\n")
    _write(root, f"{PLUGIN_DIR}/setup.pyc", "bytecode from a screen somebody opened\n")
    _write(root, f"{PLUGIN_DIR}/_vendor/paho/mqtt/client.pyc", "vendored bytecode\n")

    restore(root, backup, restore_provisioning=True, restore_settings=True)

    assert not plugin.exists()


def test_pruning_keeps_the_newest_two_snapshots(tmp_path: Path) -> None:
    """Otherwise every guided install leaves another copy of the plugin on flash.

    The newest is the way back from the install that has just succeeded, and the one
    before it is the way back from the install before that. Older ones have been
    superseded twice and nobody is going to reach for them.
    """
    backups = tmp_path / "mqttbridge-backups"
    backups.mkdir()
    for index, nonce in enumerate(
        ("aaaaaaaaaaaa", "bbbbbbbbbbbb", "cccccccccccc", "dddddddddddd")
    ):
        directory = backups / f"ha-installer-{nonce}"
        directory.mkdir()
        (directory / "snapshot.json").write_text("{}", encoding="utf-8")
        os.utime(directory, (1_700_000_000 + index, 1_700_000_000 + index))

    removed = prune_snapshots(backups)

    assert removed == ["ha-installer-aaaaaaaaaaaa", "ha-installer-bbbbbbbbbbbb"]
    assert sorted(child.name for child in backups.iterdir()) == [
        "ha-installer-cccccccccccc",
        "ha-installer-dddddddddddd",
    ]


def test_pruning_never_removes_the_snapshot_of_the_install_that_is_committing(
    tmp_path: Path,
) -> None:
    """A timestamp on these receivers is not a clock.

    Many have no battery-backed one: they boot in 1970 and jump to the real time when
    NTP answers, which can be minutes into an install and so after its snapshot was
    taken. Ordering by modification time would then rank the snapshot that is the only
    way back from the committing install as the oldest, and delete it.
    """
    backups = tmp_path / "mqttbridge-backups"
    backups.mkdir()
    for nonce, modified in (
        ("aaaaaaaaaaaa", 1_700_000_100),
        ("bbbbbbbbbbbb", 1_700_000_200),
        # Taken last, stamped before the receiver's clock was corrected.
        ("cccccccccccc", 1_000_000_000),
    ):
        directory = backups / f"ha-installer-{nonce}"
        directory.mkdir()
        os.utime(directory, (modified, modified))

    removed = prune_snapshots(backups, keep_name="ha-installer-cccccccccccc")

    assert removed == ["ha-installer-aaaaaaaaaaaa"]
    assert sorted(child.name for child in backups.iterdir()) == [
        "ha-installer-bbbbbbbbbbbb",
        "ha-installer-cccccccccccc",
    ]


def test_pruning_after_a_failed_install_still_leaves_exactly_two(tmp_path: Path) -> None:
    """A failed run's snapshot is an ordinary candidate, not a third thing kept.

    Pruning only runs once a transaction has committed, so a run that rolls back leaves
    its snapshot behind — as it should, it is the evidence — and the directory is one
    fuller than the rule allows until the next install succeeds. Observed on a receiver
    after the rollback drill of 2026-09-22: two snapshots from earlier successes and one
    from the failed run. The next success has to bring that back to two.
    """
    backups = tmp_path / "mqttbridge-backups"
    backups.mkdir()
    for nonce, modified in (
        ("aaaaaaaaaaaa", 1_700_000_100),
        ("bbbbbbbbbbbb", 1_700_000_200),
        # The run that rolled back.
        ("cccccccccccc", 1_700_000_300),
        # The install that is committing now.
        ("dddddddddddd", 1_700_000_400),
    ):
        directory = backups / f"ha-installer-{nonce}"
        directory.mkdir()
        os.utime(directory, (modified, modified))

    removed = prune_snapshots(backups, keep_name="ha-installer-dddddddddddd")

    assert removed == ["ha-installer-aaaaaaaaaaaa", "ha-installer-bbbbbbbbbbbb"]
    assert sorted(child.name for child in backups.iterdir()) == [
        "ha-installer-cccccccccccc",
        "ha-installer-dddddddddddd",
    ]


def test_pruning_touches_nothing_it_did_not_make(tmp_path: Path) -> None:
    """`rmtree` down a symlink would leave the backups directory altogether."""
    backups = tmp_path / "mqttbridge-backups"
    backups.mkdir()
    outside = tmp_path / "somebody-elses-data"
    outside.mkdir()
    (outside / "keep").write_text("keep\n", encoding="utf-8")
    (backups / "ha-installer-000000000000").symlink_to(outside, target_is_directory=True)
    (backups / "manual-backup-before-the-update").mkdir()
    (backups / ".ha-installer.lock").mkdir()
    (backups / "ha-installer-111111111111.tar").write_text("an archive\n", encoding="utf-8")
    superseded = backups / "ha-installer-333333333333"
    superseded.mkdir()
    os.utime(superseded, (1_700_000_000, 1_700_000_000))
    (backups / "ha-installer-222222222222").mkdir()

    assert prune_snapshots(backups, keep=1) == ["ha-installer-333333333333"]

    assert (outside / "keep").is_file()
    assert sorted(child.name for child in backups.iterdir()) == [
        ".ha-installer.lock",
        "ha-installer-000000000000",
        "ha-installer-111111111111.tar",
        "ha-installer-222222222222",
        "manual-backup-before-the-update",
    ]


def test_pruning_a_backups_directory_that_is_not_there_is_not_an_error(
    tmp_path: Path,
) -> None:
    """It runs after the install is committed; nothing it finds may raise."""
    assert prune_snapshots(tmp_path / "never-created") == []


def test_snapshot_refuses_symlink_openwebif_shim(tmp_path: Path) -> None:
    root = tmp_path / "root"
    backup = tmp_path / "backup"
    _receiver_tree(root)
    shim = (
        root / "usr/lib/enigma2/python/Plugins/Extensions/WebInterface/"
        "WebChilds/External/MQTTBridge.py"
    )
    target = tmp_path / "outside-shim"
    target.write_text("outside\n", encoding="utf-8")
    shim.unlink()
    shim.symlink_to(target)

    with pytest.raises(ValueError, match="OpenWebif shim"):
        snapshot(root, backup)


def test_restore_refuses_unsafe_live_webif_cache_before_changes(tmp_path: Path) -> None:
    root = tmp_path / "root"
    backup = tmp_path / "backup"
    _receiver_tree(root)
    snapshot(root, backup)
    status = root / "usr/lib/opkg/status"
    status.write_text("Package: concurrent\nVersion: 1\n", encoding="utf-8")
    before = status.read_bytes()
    cache = (
        root / "usr/lib/enigma2/python/Plugins/Extensions/WebInterface/"
        "WebChilds/External/__pycache__"
    )
    shutil_target = tmp_path / "outside-cache"
    shutil_target.mkdir()
    for child in cache.iterdir():
        child.unlink()
    cache.rmdir()
    cache.symlink_to(shutil_target, target_is_directory=True)

    with pytest.raises(ValueError, match="bytecode directory"):
        restore(root, backup, restore_provisioning=True, restore_settings=True)

    assert status.read_bytes() == before


def test_incomplete_snapshot_is_rejected_before_live_files_change(tmp_path: Path) -> None:
    root = tmp_path / "root"
    backup = tmp_path / "backup"
    _receiver_tree(root)
    snapshot(root, backup)
    (backup / "plugin").rename(backup / "plugin-missing")
    before = (root / "usr/lib/opkg/status").read_bytes()

    with pytest.raises(ValueError, match="incomplete"):
        restore(root, backup, restore_provisioning=True, restore_settings=True)

    assert (root / "usr/lib/opkg/status").read_bytes() == before


def test_snapshot_refuses_symlink_plugin_directory(tmp_path: Path) -> None:
    root = tmp_path / "root"
    backup = tmp_path / "backup"
    _receiver_tree(root)
    plugin = root / "usr/lib/enigma2/python/Plugins/Extensions/MQTTBridge"
    target = tmp_path / "elsewhere"
    plugin.rename(target)
    plugin.symlink_to(target, target_is_directory=True)

    with pytest.raises(ValueError, match="symlink"):
        snapshot(root, backup)


def test_restore_refuses_live_symlink_before_metadata_changes(tmp_path: Path) -> None:
    root = tmp_path / "root"
    backup = tmp_path / "backup"
    _receiver_tree(root)
    snapshot(root, backup)
    status = root / "usr/lib/opkg/status"
    before = status.read_bytes()
    plugin = root / "usr/lib/enigma2/python/Plugins/Extensions/MQTTBridge"
    target = tmp_path / "replacement"
    plugin.rename(target)
    plugin.symlink_to(target, target_is_directory=True)

    with pytest.raises(ValueError, match="live plugin"):
        restore(root, backup, restore_provisioning=True, restore_settings=True)

    assert status.read_bytes() == before


def test_read_identity_exposes_the_binding_fields_and_never_a_secret(
    tmp_path: Path,
) -> None:
    root = tmp_path / "root"
    _write(
        root,
        "etc/enigma2/settings",
        "config.plugins.mqttbridge.host=broker.example\n"
        "config.plugins.mqttbridge.password=not-returned\n"
        "config.plugins.mqttbridge.node_id=vuuno4kse_005301\n"
        "config.plugins.mqttbridge.base_topic=enigma2/rooms\n"
        "config.plugins.mqttbridge.enabled=true\n"
        "config.plugins.mqttbridge.ha_mode=integration\n",
    )

    assert read_identity(root) == {
        "node_id": "vuuno4kse_005301",
        "base_topic": "enigma2/rooms",
        "enabled": True,
        "ha_mode": "integration",
        "friendly_name": None,
    }


def test_read_identity_reports_a_setting_that_is_not_stored_as_absent(
    tmp_path: Path,
) -> None:
    """Enigma2 writes no line for a setting still at its default, and this says so.

    A receiver measured after a working install held exactly these keys and no
    `base_topic`, because it had never been moved off `enigma2`. This used to answer
    `enigma2` for that — the right value, from a copy of the plugin's defaults kept on
    the receiver's side of the link, where it was invisible to the half that compares.
    `None` is the fact; applying the default is the caller's job.
    """
    root = tmp_path / "root"
    _write(
        root,
        "etc/enigma2/settings",
        "config.misc.keep=true\n"
        "config.plugins.mqttbridge.host=broker.example\n"
        "config.plugins.mqttbridge.node_id=vuuno4kse_005301\n"
        "config.plugins.mqttbridge.ha_mode=off\n",
    )

    assert read_identity(root) == {
        "node_id": "vuuno4kse_005301",
        "base_topic": None,
        "enabled": None,
        "ha_mode": "off",
        "friendly_name": None,
    }


def test_read_identity_tells_a_stored_empty_value_from_an_absent_one(
    tmp_path: Path,
) -> None:
    """`base_topic=` is a line, and a line is a value the receiver holds."""
    root = tmp_path / "root"
    _write(
        root,
        "etc/enigma2/settings",
        "config.plugins.mqttbridge.node_id=vuuno4kse_005301\n"
        "config.plugins.mqttbridge.base_topic=\n",
    )

    identity = read_identity(root)

    assert identity["base_topic"] == ""
    assert identity["ha_mode"] is None


def test_read_identity_of_a_receiver_with_no_settings_file_is_all_absent(
    tmp_path: Path,
) -> None:
    """Nothing stored is not the same as stored empty, and neither is a difference."""
    assert read_identity(tmp_path / "root") == {
        "node_id": None,
        "base_topic": None,
        "enabled": None,
        "ha_mode": None,
        "friendly_name": None,
    }


def test_read_identity_reports_the_name_the_receiver_stores_verbatim(
    tmp_path: Path,
) -> None:
    """The name is reported as stored, so a reinstall can carry it forward.

    Nothing compares it — a receiver may be called anything — but a guided reinstall
    whose name field was left empty has to be able to put back the name the household
    reads, and it can only do that if this reports it rather than a tidied version of
    it. Leading and trailing spaces are left on: deciding whether they mean "no name"
    belongs to the side that decides what to write.
    """
    root = tmp_path / "root"
    _write(
        root,
        "etc/enigma2/settings",
        "config.plugins.mqttbridge.node_id=vuuno4kse_005301\n"
        "config.plugins.mqttbridge.friendly_name= Living room receiver \n",
    )

    identity = read_identity(root)

    assert identity["friendly_name"] == " Living room receiver "


def test_read_identity_tells_a_receiver_with_an_empty_name_from_one_with_none(
    tmp_path: Path,
) -> None:
    """A receiver that has never run its plugin stores no name at all."""
    root = tmp_path / "root"
    _write(root, "etc/enigma2/settings", "config.plugins.mqttbridge.friendly_name=\n")

    assert read_identity(root)["friendly_name"] == ""
    assert read_identity(tmp_path / "other")["friendly_name"] is None


def test_verify_manifest_checks_actual_installed_bytes(tmp_path: Path) -> None:
    root = tmp_path / "root"
    installed = _write(root, "usr/lib/enigma2/plugin.py", "exact bytes")
    digest = hashlib.sha256(installed.read_bytes()).hexdigest()
    manifest = tmp_path / "manifest"
    manifest.write_text(f"{digest}  /usr/lib/enigma2/plugin.py\n", encoding="ascii")

    verify_manifest(root, manifest)
    installed.write_text("tampered", encoding="utf-8")
    with pytest.raises(ValueError, match="digest"):
        verify_manifest(root, manifest)


def test_snapshot_metadata_must_be_typed_and_complete(tmp_path: Path) -> None:
    root = tmp_path / "root"
    backup = tmp_path / "backup"
    _receiver_tree(root)
    snapshot(root, backup)
    (backup / "snapshot.json").write_text(json.dumps({"plugin": "yes"}), encoding="utf-8")

    with pytest.raises(ValueError, match="metadata"):
        restore(root, backup, restore_provisioning=True, restore_settings=True)


def test_verify_manifest_ignores_files_the_image_added_beside_the_plugin(
    tmp_path: Path,
) -> None:
    """The receiver byte-compiles what it imports, and that is not a tampered install.

    The manifest lists the `.py` files the IPK ships. OpenViX writes `.pyc` files next
    to them the first time the plugin loads, so an install that verified only by "these
    files and nothing else" would fail on every healthy receiver. Verification proves
    the listed bytes are the shipped bytes; it deliberately says nothing about extras.
    """
    root = tmp_path / "root"
    installed = _write(root, "usr/lib/enigma2/plugin.py", "exact bytes")
    digest = hashlib.sha256(installed.read_bytes()).hexdigest()
    manifest = tmp_path / "manifest"
    manifest.write_text(f"{digest}  /usr/lib/enigma2/plugin.py\n", encoding="ascii")
    _write(root, "usr/lib/enigma2/__pycache__/plugin.cpython-312.pyc", "bytecode")
    _write(root, "usr/lib/enigma2/plugin.pyc", "bytecode")

    verify_manifest(root, manifest)


def _owner(lock_dir: Path) -> dict:
    return json.loads((lock_dir / "owner.json").read_text(encoding="ascii"))


def test_the_durable_lock_refuses_a_second_live_transaction(tmp_path: Path) -> None:
    """Two installs on one receiver would interleave two rollbacks."""
    lock_dir = tmp_path / "lock"
    claim_transaction(lock_dir)

    with pytest.raises(FileExistsError):
        claim_transaction(lock_dir)

    release_transaction(lock_dir)
    assert not lock_dir.exists()


def test_a_lock_from_before_the_receiver_rebooted_is_reclaimed(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """A box pulled out of the wall mid-install must not be locked out for ever.

    The lock is a directory on flash, so it survives the reboot that killed the process
    holding it. The boot id says so without having to guess from a timestamp.
    """
    lock_dir = tmp_path / "lock"
    claim_transaction(lock_dir)
    stale = {**_owner(lock_dir), "boot_id": "00000000-0000-0000-0000-000000000000"}
    (lock_dir / "owner.json").write_text(json.dumps(stale), encoding="ascii")

    claim_transaction(lock_dir)

    assert _owner(lock_dir)["boot_id"] == boot_id()
    assert "reclaiming stale installer lock" in capsys.readouterr().err


def test_a_lock_older_than_any_plausible_install_is_reclaimed(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """The boot id only helps across a reboot; a crashed process leaves the same wedge."""
    lock_dir = tmp_path / "lock"
    claim_transaction(lock_dir)
    stale = {
        **_owner(lock_dir),
        "started": int(time.time()) - STALE_LOCK_SECONDS - 1,
        "uptime": (uptime() or 0.0) - STALE_LOCK_SECONDS - 1,
    }
    (lock_dir / "owner.json").write_text(json.dumps(stale), encoding="ascii")

    claim_transaction(lock_dir)

    assert _owner(lock_dir)["started"] > stale["started"]
    assert "reclaiming stale installer lock" in capsys.readouterr().err


def test_a_lock_that_is_merely_slow_is_still_respected(tmp_path: Path) -> None:
    """Reclaiming an install that is only taking its time would start a second one."""
    lock_dir = tmp_path / "lock"
    claim_transaction(lock_dir)
    recent = {**_owner(lock_dir), "started": int(time.time()) - STALE_LOCK_SECONDS + 60}
    (lock_dir / "owner.json").write_text(json.dumps(recent), encoding="ascii")

    with pytest.raises(FileExistsError):
        claim_transaction(lock_dir)


@pytest.mark.parametrize("content", ["", "not json", json.dumps(["a list"])])
def test_a_lock_with_an_unreadable_owner_record_is_reclaimed_once_it_is_old(
    tmp_path: Path, content: str
) -> None:
    """A claim that died mid-write is a wedge with nobody behind it.

    Age has to come into it, because the same unreadable directory is what a claim that
    started a millisecond ago looks like.
    """
    lock_dir = tmp_path / "lock"
    claim_transaction(lock_dir)
    (lock_dir / "owner.json").write_text(content, encoding="ascii")
    old = time.time() - STALE_LOCK_SECONDS - 60
    os.utime(lock_dir, (old, old))

    claim_transaction(lock_dir)

    assert _owner(lock_dir)["boot_id"] == boot_id()


def test_an_owner_record_that_is_not_an_object_is_reclaimed(tmp_path: Path) -> None:
    """Valid JSON that is not a record cannot have been written by a claim."""
    lock_dir = tmp_path / "lock"
    claim_transaction(lock_dir)
    (lock_dir / "owner.json").write_text(json.dumps({}), encoding="ascii")

    claim_transaction(lock_dir)

    assert _owner(lock_dir)["boot_id"] == boot_id()


def test_releasing_a_lock_without_an_owner_is_refused(tmp_path: Path) -> None:
    """`release` removes an installer lock, not any directory it is pointed at."""
    lock_dir = tmp_path / "lock"
    lock_dir.mkdir()

    with pytest.raises(ValueError, match="owner"):
        release_transaction(lock_dir)


def test_the_boot_id_is_empty_rather_than_fatal_on_a_kernel_without_one(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Then the age bound is the only staleness rule, which is still better than none."""
    monkeypatch.setattr(installer_helper, "BOOT_ID_PATH", tmp_path / "nothing-here")

    assert boot_id() == ""
    lock_dir = tmp_path / "lock"
    claim_transaction(lock_dir)
    assert _owner(lock_dir)["boot_id"] == ""
    with pytest.raises(FileExistsError):
        claim_transaction(lock_dir)
